export const EVENT_ICONS=['setup','people','flag','warmup','borrow','basket','break','cavalry','tug','relay','buffer','trophy','camera','cleanup','finish'];
export const EVENT_GAMES={4:'borrow',5:'basket',7:'cavalry',8:'tug',9:'relay'};
export const GAME_EVENTS={borrow:4,basket:5,cavalry:7,tug:8,relay:9};
export const GAME_NAMES={borrow:'Borrow-a-Thing',basket:'Ball Basket',cavalry:'Cavalry Game',tug:'Tug-of-War',relay:'Team Relay'};
export const NOTES=[
 ['Committee in at 11:40; field and gear ready by 12:00.','Check judges, first aid and the water station.'],
 ['Five mixed teams, around 6–8 people each.','Draw colour sticks from separate men’s and women’s pools.','Leaders count their team and sort substitutions.'],
 ['Point out first aid, boundaries and the stop signal.','Join in if you’re comfortable; stop for an injury.'],
 ['Five-minute warm-up together.','Check shoes and make sure everyone is ready.'],
 ['All five teams play, one runner each per round.','6 rounds; optional 7th. Rotate runners.','Success order: 5 / 4 / 3 / 2 / 2 points. Fail or timeout: 0.','Add the round points to get the game placing.'],
 ['Two 30-second attempts per team, taking turns.','Best ball count wins.','Same ball supply, distance and player count for each team.'],
 ['20 minutes for food, water and a breather.','Back for Cavalry at 13:30.'],
 ['Women first, then men. Each horse: 3 bases + 1 rider.','All-in battle; only riders wear hachimaki.','Pick the arena teams, start the timer, tap each horse when it’s out.','Last standing to first out: 5 / 4 / 3 / 2 / 1 points. Add both rounds.'],
 ['Draw opponents: preliminary → 2 semifinals → final.','3 teams go straight to the semifinals. Same number of pullers on each side.','Suggested timer: 60s; reset and replay for 30s if tied.','Agree places 3–5 before awarding championship points.'],
 ['All five teams race in all three rounds.','Baton ~8 min · Three-legged ~10 min · Spoon & ball ~8 min.','Each round: 5 / 4 / 3 / 2 / 1 points. Add them for the game placing.','Keep runner/pair counts equal; rotate extra members.'],
 ['10 minutes for delays, score checks or a tie-breaker.','Leave enough time to clear the field by 16:00.'],
 ['Each game gives 5 / 4 / 3 / 2 / 1 championship points.','Settle missing places and ties before calling the results.','Overall tie: most firsts, then a short tie-breaker.','Winner coupons / gift vouchers planned.'],
 ['All five teams together for the photo.','Keep gear and bags together for cleanup.'],
 ['Pack the gear, pick up rubbish and check your belongings.','Field clear by 16:00.'],
 ['All done. Field clear by 16:00.'],
];
export const COMMITTEE=[
 ['Committee in at 11:40. Mark the boundaries and set up the whistle, timer and scores.','Assign the assistant judge, two first-aid volunteers and gear / water cover.','Check the field, gear and water before everyone arrives.'],
 ['Match the colour-stick counts to attendance.','Count teams, note names and update the team desk.','Invite anyone with a health concern or injury to speak privately with first aid.'],
 ['Show the stop signal and point out first aid.','Check contact-game arrangements; keep health details private.'],
 ['Lead a gentle warm-up.','Check the field, shoes and who’s ready to play.'],
 ['~45 cards ready; draw 5 from the round’s category, without replacement.','R1–2: 90s · R3–6: 120s · optional R7: 90s.','Check each finish before tapping Success; Fail gives 0.','Ask before borrowing. No medication, valuables or first-aid staff on duty.'],
 ['Test the basket and mark a clear zone around it.','Reset the same ball supply; count balls in the basket.','30s per attempt; use the better count. Suggested tie-break: 15s if there’s time.'],
 ['Refill food and water, and pick up rubbish.','Check on teams while the next game is set up.'],
 ['Check 3 bases + 1 rider per horse; explain the out signal and timer.','Judge watches the arena; a separate scorer taps horses as they go out.','Watch balance and boundaries. Stop for injury; a fall is not a scoring move.'],
 ['Check equal puller counts, the rope and the next matchup.','No rope wrapping or sudden release. Stop for injury.','Save the winner and settle tied matches / places 3–5.'],
 ['Set out batons, soft quick-release ties, spoons and balls.','Watch lanes, finish order and equal runner/pair counts.','No forced pairs or dragging. Ball drop: stop, replace, resume there; keep fingers off it while moving.'],
 ['Check scores and finish any tie-breaker.','Get prizes and the photo ready; keep cleanup time.'],
 ['Check all five game placings and any ties.','Call the final results and hand out vouchers.'],
 ['Mario / Cindy: gather teams and take photos/video.','Leaders: get everyone together and keep access clear.'],
 ['Count the gear; pick up rubbish and belongings.','Do one last field check before 16:00.'],
 ['Check the field is clear and all gear is packed.'],
];

// Department notes use the same 15 event indices as the rundown.
export const DEPARTMENTS=[
 {id:'director',name:'Director / scores',general:['Committee in at 11:40; ready by 12:00. Run the whistle and timer.','Save scores during pauses; the assistant watches live contact games.','Overall: add game placing points (5 / 4 / 3 / 2 / 1). Ties: most firsts, then a short tie-breaker.'],notes:[
  ['Committee in at 11:40; setup finished by 12:00.','Set up the whistle, timer and score desk.','Assign the assistant judge and check first-aid cover.'],
  ['Update team names and numbers in the team desk.'],
  ['Show the stop signal and explain the boundaries.'],
  ['Lead the five-minute warm-up.'],
  ['R1–2: 90s · R3–6: 120s · optional R7: 90s.','Cards: Easy (1–2), Medium (3, 5), Borrow-a-Person (4), Funny/Chaos (6).','Tap Success in finish order, only after the judge checks it. Fail gives 0.'],
  ['Run two 30s attempts per team. Save each count; the better one is used.','If tied, a 15s playoff is suggested if there’s time.'],
  ['Check the scores so far; be ready to restart at 13:30.'],
  ['Set the round timer and arena teams.','Keep a judge watching contact while a separate scorer taps horses as they go out.'],
  ['Lock the draw, then run each match and save the winner.','Suggested timer: 60s, then a reset and 30s replay if tied.','Agree places 3–5 before awarding points.'],
  ['Record the finish order in each round.','Leave ~4 min for totals and changeovers.'],
  ['Check missing scores and settle ties.','Keep cleanup on time.'],
  ['Overall total: add each game’s placing points (5 / 4 / 3 / 2 / 1).','Check all five placings before calling the winner.','Overall tie: most firsts, then a short tie-breaker.'],
  ['Keep the photo to 10 minutes so cleanup can start.'],
  ['Do the final field check with equipment.'],
  ['Check the field is clear by 16:00.'],
 ]},
 {id:'judges',name:'Judges',general:['Assistant judge: watch boundaries, finishes and equal player counts.','Call results clearly for the scorer; get the next matchup ready.','Stop play for an injury or unsafe contact.'],notes:[
  ['Walk the field and mark the boundaries.','Check the basket and rope before play.'],
  ['Help keep the team draw balanced.'],
  ['Make sure everyone can see and hear the stop signal.'],
  ['Check the field and footwear.'],
  ['Check each item/person and the finish order.','No medication, valuables or first-aid staff on duty.'],
  ['Count balls in the basket; check equal balls, distance and player counts.','Watch stray balls and keep the basket zone clear.'],
  ['Prepare the Cavalry arena.'],
  ['Check 3 bases + 1 rider per horse, in the same-gender round.','Watch balance, contact and boundaries; call horses out clearly.','Stop for injury. A fall or collapse is not a scoring move.'],
  ['Check equal puller counts and the next matchup.','No rope wrapping, sudden release or play through injury.','Call the winner clearly for the scorer.'],
  ['Watch lanes and finish order; keep runner/pair counts equal.','No forced pairs or dragging.','Ball drop: stop, replace, resume there; keep fingers off it while moving.'],
  ['Help settle any tie-breaker.'],
  ['Check any disputed finish or placing before results are called.'],
  ['Keep the photo area and access routes clear.'],
  ['Help with the final field check.'],
  [],
 ]},
 {id:'first-aid',name:'First aid',general:['Ask privately about any history of heart disease, asthma, allergies, diabetes, seizures or fainting; check current injuries.','Sharing is optional. Check access to their own emergency medication; keep health details private.','Two volunteers TBA: confirm qualified cover and who to call in an emergency.','Stay easy to find through games and cleanup; keep the first-aid spot accessible.'],notes:[
  ['Assign the two volunteers; check qualified cover and who to call in an emergency.','Make the first-aid spot easy to find; be ready for private health checks at registration.'],
  ['Ask privately about any history of heart disease, asthma, allergies, diabetes, seizures or fainting; check current injuries.','Sharing is optional. Keep names and health details with first aid.','Check access to their own emergency medication before they play.'],
  ['Tell everyone where to find you.'],
  ['Be ready for anyone who needs help or wants to sit out.'],
  ['Stay on duty; first-aid staff are not part of borrowing tasks.'],
  ['Keep first aid easy to reach during play.'],
  ['Check anyone who feels unwell; keep help available.'],
  ['Be ready beside the arena. Stop play for an injury.'],
  ['Keep first aid easy to reach. Stop play for an injury.'],
  ['Keep an eye out for anyone needing help between rounds.'],
  ['Check any outstanding concerns before results.'],
  ['Stay available until the program ends.'],
  ['Keep access to first aid clear during the photo.'],
  ['Stay available during cleanup.'],
  [],
 ]},
 {id:'equipment',name:'Equipment',general:['Check the field, basket and rope; agree who’s on gear for each game.','Game kit: ~45 cards, ping-pong balls, laundry basket, hachimaki, rope, batons, soft quick-release ties and spoons.','Bring the mat, icebox, cart, umbrellas, pens and gear bags. Have the next game ready during changeovers.','Count everything back in; field clear by 16:00.'],notes:[
  ['Set out cones, draw sticks, game gear and water.','Check the basket and rope, and mark clear play areas.','Bring the mat, icebox, cart, umbrellas, pens and gear bags.'],
  ['Adjust both colour-stick pools to the actual attendance.'],
  ['Keep boundaries easy to see.'],
  ['Clear anything loose from the warm-up area.'],
  ['Have ~45 cards ready. Draw 5 from each round’s category.','Keep used cards out of the deck.'],
  ['Test basket stability, visibility and wind; keep it still during the attempt.','Mark a clear zone and reset the same ball supply between attempts.'],
  ['Set out hachimaki and prepare the Cavalry arena.'],
  ['Give hachimaki to riders only.','Keep loose gear out of the arena.'],
  ['Check rope suitability and capacity before use.','Prepare the next matchup during resets.'],
  ['Set out batons, soft quick-release ties, spoons and ping-pong balls.','Check each team has the same setup.'],
  ['Get the prizes ready; start packing unused gear.'],
  ['Have the winner coupons / vouchers ready.'],
  ['Keep gear and bags together for cleanup.'],
  ['Count balls, basket, ropes, batons, cloths and cones.','Check for gear left on the field.'],
  ['Check all gear is packed and the field is clear.'],
 ]},
 {id:'food-water',name:'Food & water',general:['Agree who’s covering food and water at the break.','Keep supplies easy to find and topped up.','Clear rubbish at the break and pack the station during cleanup.'],notes:[
  ['Set up food and water where people can find them.'],
  [],
  [],
  [],
  [],
  [],
  ['Refill food and water.','Pick up rubbish before the next game.'],
  [],
  [],
  [],
  ['Collect rubbish and pack anything no longer needed.'],
  [],
  [],
  ['Pack leftover supplies and clear the station.'],
  [],
 ]},
 {id:'comms',name:'Comm',general:['Mario / Cindy: announcements, team calls and photos/video.','Call the next team or round so changeovers stay quick.','Gather all five teams for the group photo.'],notes:[
  ['Check announcements and phones for photos/video.'],
  ['Call people over for the team draw.'],
  ['Introduce the judges and first-aid team.'],
  ['Gather everyone for the warm-up.'],
  ['Call the next runner and round clearly.'],
  ['Call the next team while the basket is reset.'],
  ['Let teams know Cavalry starts at 13:30.'],
  ['Call the women’s round, then the men’s round.'],
  ['Call the next matchup from the bracket.'],
  ['Call each relay round and give teams time to get ready.'],
  ['Get teams ready for results and the photo.'],
  ['Announce the final results once the scores are checked.'],
  ['Mario / Cindy: gather all five teams and take photos/video.'],
  ['Remind everyone to collect bags and help clean up.'],
  [],
 ]},
 {id:'team-leaders',name:'Team leaders',general:['Count members, sort substitutions and get your team ready.','Keep player counts equal and rotate runners/pairs; nobody has to join in.','Check on your team and pass concerns to first aid privately.'],notes:[
  [],
  ['Count members, note names and sort substitutions.','Invite anyone with a health concern or injury to speak privately with first aid.'],
  ['Check everyone knows the boundaries and stop signal.','Pass any concerns to first aid privately.'],
  ['Check who’s ready to play; nobody has to join in.'],
  ['Send one runner per round. Rotate so everyone willing gets a turn.','Ask before borrowing an item or person.'],
  ['Keep player counts equal and have the team ready for both attempts.'],
  ['Check on your team; back for Cavalry at 13:30.'],
  ['Sort 3 bases + 1 rider per horse for the women’s / men’s round.','Check your team knows the out and stop signals.'],
  ['Match the agreed puller count and be ready for your matchup.','No wrapping the rope or sudden release.'],
  ['Keep runner/pair counts equal and rotate extra members.','No forced pairs or dragging.'],
  ['Stay ready if a tie-breaker is needed.'],
  ['Gather the team for results.'],
  ['Get everyone together quickly and keep access clear.'],
  ['Check everyone has their belongings; help collect rubbish.'],
  ['Check your team is ready to leave and nothing is left behind.'],
 ]},
];
