export const EVENT_ICONS=['setup','people','flag','warmup','borrow','basket','break','cavalry','tug','relay','buffer','trophy','camera','cleanup','finish','prayer'];
export const EVENT_GAMES={4:'borrow',5:'basket',7:'cavalry',8:'tug',9:'relay'};
export const GAME_EVENTS={borrow:4,basket:5,cavalry:7,tug:8,relay:9};
export const orderedSchedule=schedule=>schedule.map((event,eventIndex)=>({...event,eventIndex})).sort((a,b)=>a.start.localeCompare(b.start));
export const GAME_NAMES={borrow:'Borrow-a-Thing',basket:'Ball Basket',cavalry:'Cavalry Game',tug:'Tug-of-War',relay:'Team Relay'};
export const SUPPLIES={
 have:[
  {name:'Mat'},
  {name:'Whistle ×1'},
  {name:'Icebox'},
  {name:'Transport cart'},
  {name:'Umbrellas'},
  {name:'Pens / markers'},
  {name:'Phones / timer'},
  {name:'Equipment bags'},
 ],
 get:[
  {name:'Coated work gloves',links:[{label:'Coupang',url:'https://www.coupang.com/vp/products/7897300869'}]},
  {name:'Cones',links:[{label:'Coupang',url:'https://www.coupang.com/vp/products/8508042796'}]},
  {name:'Lightweight ping-pong balls',detail:'Basket + Relay',links:[{label:'Coupang',url:'https://www.coupang.com/vp/products/8371729751'}]},
  {name:'Batons',links:[{label:'Coupang',url:'https://www.coupang.com/vp/products/8710269702'}]},
  {name:'Hachimaki / rider cloth',detail:'Riders only · linked alternative is 소고띠',links:[{label:'Gmarket alt.',url:'https://item.gmarket.co.kr/Item?goodsCode=3112127158'}]},
  {name:'Colour draw sticks',detail:'Separate men’s / women’s pools',action:'Prepare'},
  {name:'Borrow-a-Thing cards',detail:'~45 cards; 30–35 used',action:'Print / prepare'},
  {name:'Lightweight laundry basket',action:'Find / borrow'},
  {name:'Tug-of-war rope',detail:'Check suitability before use',action:'Find / borrow'},
  {name:'Soft quick-release leg ties',detail:'Three-legged relay',action:'Find / borrow'},
  {name:'Spoons',detail:'1 per team',action:'Find / borrow'},
  {name:'Food & water',action:'Arrange'},
  {name:'Winner coupons / gift vouchers',action:'Planned'},
 ],
};
export const NOTES=[
 ['Committee in at 11:40; field and gear ready by 12:00.','Check judges, first aid and the water station.'],
 ['Five mixed teams, around 6–8 people each.','Draw colour sticks from separate men’s and women’s pools.','Leaders count their team and sort substitutions.'],
 ['Point out first aid, boundaries and the stop signal.','Join in if you’re comfortable; stop for an injury.'],
 ['Five-minute warm-up together.','Check shoes and make sure everyone is ready.'],
 ['All five teams play, one runner each per round.','6 rounds; optional 7th. Rotate runners.','Success order: 5 / 4 / 3 / 2 / 2 points. Fail or timeout: 0.','Add the round points to get the game placing.'],
 ['Two 30-second attempts per team, taking turns.','Best ball count wins.','Same ball supply, distance and player count for each team.'],
 ['20 minutes for food, water and a breather.','Back for Cavalry at 13:30.'],
 ['Women first, then men. Each horse: 3 bases + 1 rider.','All-in battle; only riders wear hachimaki.','Pick the arena teams, start the timer, tap each horse when it’s out.','Last standing to first out: 5 / 4 / 3 / 2 / 1 points. Add both rounds.'],
 ['Draw opponents: preliminary → 2 semifinals → final.','3 teams go straight to the semifinals. Same number of pullers on each side.','Suggested timer: 60s; reset and replay for 30s if tied.','Final winner takes first, runner-up second; semifinal losers share third.'],
 ['All five teams race in all three rounds.','Baton ~8 min · Three-legged ~10 min · Spoon & ball ~8 min.','Each round: 5 / 4 / 3 / 2 / 1 points. Add them for the game placing.','Keep runner/pair counts equal; rotate extra members.'],
 ['10 minutes for delays, score checks or a tie-breaker.','Leave enough time to clear the field by 16:00.'],
 ['Each game gives 5 / 4 / 3 / 2 / 1 championship points.','Finish all rounds before calling the results; tied game scores share points.','Overall tie: most firsts, then a short tie-breaker.','Winner coupons / gift vouchers planned.'],
 ['All five teams together for the photo.','Keep gear and bags together for cleanup.'],
 ['Pack the gear, pick up rubbish and check your belongings.','Field clear by 16:00.'],
 ['All done. Field clear by 16:00.'],
 ['A short opening Prayer before the welcome and safety briefing.','Gather all five teams so everyone can hear.'],
];
export const COMMITTEE=[
 ['Committee in at 11:40. Mark the boundaries and set up the whistle, timer and scores.','Assign the assistant judge, two first-aid volunteers and gear / water cover.','Check the field, gear and water before everyone arrives.'],
 ['Match the colour-stick counts to attendance.','Count teams, note names and update the team desk.','Invite anyone with a health concern or injury to speak privately with first aid.'],
 ['Show the stop signal and point out first aid.','Check contact-game arrangements; keep health details private.'],
 ['Lead a gentle warm-up.','Check the field, shoes and who’s ready to play.'],
 ['~45 cards ready; draw 5 from the round’s category, without replacement.','R1–2: 90s · R3–6: 120s · optional R7: 90s.','Check each finish before tapping Success; Fail gives 0.','Ask before borrowing. No medication, valuables or first-aid staff on duty.'],
 ['Test the basket and mark a clear zone around it.','Reset the same ball supply; count balls in the basket.','Start each 30s attempt before counting; use the better count. Equal best counts share points.'],
 ['Refill food and water, and pick up rubbish.','Check on teams while the next game is set up.'],
 ['Check 3 bases + 1 rider per horse; explain the out signal and timer.','Judge watches the arena; a separate scorer taps horses as they go out.','Watch balance and boundaries. Stop for injury; a fall is not a scoring move.'],
 ['Check equal puller counts, the rope and the next matchup.','No rope wrapping or sudden release. Stop for injury.','Save each winner after starting the timer; semifinal losers share third place.'],
 ['Set out batons, soft quick-release ties, spoons and balls.','Watch lanes, finish order and equal runner/pair counts.','No forced pairs or dragging. Ball drop: stop, replace, resume there; keep fingers off it while moving.'],
 ['Check scores and finish any tie-breaker.','Get prizes and the photo ready; keep cleanup time.'],
 ['Check all five game placings and any ties.','Call the final results and hand out vouchers.'],
 ['Mario / Cindy: gather teams and take photos/video.','Leaders: get everyone together and keep access clear.'],
 ['Count the gear; pick up rubbish and belongings.','Do one last field check before 16:00.'],
 ['Check the field is clear and all gear is packed.'],
 ['Confirm who leads Prayer before the teams gather.','Call all five teams together; move straight into the opening briefing.'],
];

// Department notes use the same 16 stable event indices as the rundown.
export const DEPARTMENTS=[
 {id:'director',name:'Director / scores',general:['Committee in at 11:40; ready by 12:00. Run the whistle and timer.','Start each timer before scoring; keep a separate judge watching contact games.','Read back each result with the judge before saving; check every round is finished.','Call pauses and changeovers clearly; tell Comm if the schedule slips.','Overall: add game placing points (5 / 4 / 3 / 2 / 1). Ties: most firsts, then a short tie-breaker.'],notes:[
  ['Committee in at 11:40; setup finished by 12:00.','Set up the whistle, timer and score desk.','Assign the assistant judge and check first-aid cover.'],
  ['Update team names and numbers in the team desk.','Confirm five leaders and who handles team substitutions.'],
  ['Show the start and stop signals, boundaries and first-aid spot.','Check every team can hear before the first game.'],
  ['Lead the five-minute warm-up.','Confirm the first runners and judge are ready before the start.'],
  ['R1–2: 90s · R3–6: 120s · optional R7: 90s.','Cards: Easy (1–2), Medium (3, 5), Borrow-a-Person (4), Funny/Chaos (6).','Tap Success in finish order, only after the judge checks it. Fail gives 0.'],
  ['Run two 30s attempts per team. Save each count after the judge confirms it; the better one is used.','Equal best counts share a place and points.'],
  ['Check completed game points in Scores; be ready to restart at 13:30.','Confirm gear, water and judge cover before the next game.'],
  ['Set the round timer and arena teams before the start.','Keep a judge watching contact while a separate scorer taps horses as they go out.','Read back the out order with the judge before closing the round.'],
  ['Lock the draw, then run each match and save the confirmed winner.','Suggested timer: 60s, then a reset and 30s replay if tied.','The final sends points automatically; semifinal losers share third place.'],
  ['Record the finish order in each round after the judge confirms it.','Leave ~4 min for totals and changeovers.'],
  ['Check missing scores and settle ties.','Keep cleanup on time.'],
  ['Overall total: add each game’s placing points (5 / 4 / 3 / 2 / 1).','Check all five games are finished and their points appear in Scores before calling the winner.','Overall tie: most firsts, then a short tie-breaker.'],
  ['Keep the photo to 10 minutes so cleanup can start.'],
  ['Do the final field check with equipment.','Check any borrowed gear is accounted for.'],
  ['Check the field is clear by 16:00.'],
  ['Confirm who leads Prayer and keep it brief.','Let Comm gather the teams; follow with the opening and safety briefing.'],
 ]},
 {id:'judges',name:'Judges',general:['Assistant judge: watch boundaries, finishes and equal player counts.','Explain the start, stop and finish signals before each game.','Call results clearly; have the scorer read them back before saving.','Keep the next matchup ready; settle disputed results while play is paused.','Stop play for an injury or unsafe contact.'],notes:[
  ['Walk the field and mark the boundaries.','Check the basket and rope before play.','Agree who watches each finish or boundary and who calls results.'],
  ['Help keep the team draw balanced.','Agree player counts with the leaders before each game.'],
  ['Show the start and stop signals where everyone can see them.','Explain where players finish and who confirms the result.'],
  ['Check the field and footwear.','Keep waiting players clear of the first game’s course.'],
  ['Check each item/person and call the finish order before Success is tapped.','Confirm the runner asked before borrowing.','No medication, valuables or first-aid staff on duty.'],
  ['Count balls in the basket after the stop signal; confirm the count with the scorer.','Check equal balls, distance and player counts for both attempts.','Watch stray balls and keep the basket zone clear.'],
  ['Prepare the Cavalry arena.','Agree who watches the out order and who watches boundaries.'],
  ['Check 3 bases + 1 rider per horse, in the same-gender round.','Watch balance, contact and boundaries; call horses out clearly.','Stop for injury. A fall or collapse is not a scoring move.'],
  ['Check equal puller counts and the next matchup.','No rope wrapping, sudden release or play through injury.','Call the winner clearly for the scorer before teams leave the rope.'],
  ['Watch lanes and finish order; keep runner/pair counts equal.','No forced pairs or dragging.','Ball drop: stop, replace, resume there; keep fingers off it while moving.'],
  ['Help settle any tie-breaker; explain the rule before the start.'],
  ['Check any disputed finish or placing before results are called.'],
  ['Keep the photo area and access routes clear.'],
  ['Help with the final field check.'],
  [],
  ['Help gather teams outside the playing areas; keep access clear.'],
 ]},
 {id:'first-aid',name:'First aid',general:['Ask privately about any history of heart disease, asthma, allergies, diabetes, seizures or fainting; check current injuries.','Sharing is optional. Check access to their own emergency medication; keep health details private.','Two volunteers TBA: confirm qualified cover and who to call in an emergency.','Agree how judges call for help; know the park entrance and keep emergency access clear.','Stay easy to find through cleanup; hand over cover before taking a break.'],notes:[
  ['Assign the two volunteers; check qualified cover and who to call in an emergency.','Make the first-aid spot easy to find; be ready for private health checks at registration.','Check the park entrance and clear access with equipment.'],
  ['Ask privately about any history of heart disease, asthma, allergies, diabetes, seizures or fainting; check current injuries.','Sharing is optional. Keep names and health details with first aid.','Check access to their own emergency medication before they play.'],
  ['Tell everyone where to find you and how to call for help.','Keep a clear route through the gathered teams.'],
  ['Be ready for anyone who needs help or wants to sit out.'],
  ['Stay on duty; first-aid staff are not part of borrowing tasks.'],
  ['Keep first aid easy to reach during play.'],
  ['Check anyone who feels unwell; keep help available.','Hand over cover before taking your own food or water break.'],
  ['Be ready beside the arena, outside the playing area. Stop play for an injury.','Check the judges know how to call for help and keep the route clear.'],
  ['Keep first aid easy to reach. Stop play for an injury.'],
  ['Keep an eye out for anyone needing help between rounds.','Keep waiting teams and bags clear of the route to first aid.'],
  ['Check any outstanding concerns before results.'],
  ['Stay available until the program ends.'],
  ['Keep access to first aid clear during the photo.'],
  ['Stay available during cleanup; keep access clear while gear is packed.'],
  ['Check any outstanding concern has been handed over before leaving.'],
  ['Stay easy to find; leave a clear route through the group.'],
 ]},
 {id:'equipment',name:'Equipment',general:['Check the field, basket and rope; agree who’s on gear for each game.','Game kit: ~45 cards, ping-pong balls, laundry basket, hachimaki, rope, batons, soft quick-release ties and spoons.','Bring the mat, icebox, cart, umbrellas, pens and gear bags.','Count the kit before leaving; hand over to the next helper and have the next game ready.','Keep spare gear off the course; count everything back in and clear the field by 16:00.'],notes:[
  ['Set out cones, draw sticks, game gear and water.','Check the basket and rope, and mark clear play areas.','Check the inventory; bring the mat, icebox, cart, umbrellas, pens and gear bags.'],
  ['Adjust both colour-stick pools to the actual attendance.','Keep the men’s and women’s pools separate; collect sticks after the draw.'],
  ['Keep boundaries easy to see and access routes clear.'],
  ['Clear anything loose from the warm-up area.','Keep the first game’s kit ready off the course.'],
  ['Have ~45 cards ready. Draw 5 from each round’s category.','Keep used cards out of the deck; sort the next category during resets.'],
  ['Test basket stability, visibility and wind; keep it still during the attempt.','Mark a clear zone and reset the same ball supply between attempts.','Collect stray balls before the next team starts.'],
  ['Set out hachimaki and prepare the Cavalry arena.','Hand over gear cover before taking a break.'],
  ['Give hachimaki to riders only.','Keep loose gear out of the arena; collect cloths after each round.'],
  ['Check rope suitability and capacity before use; have gloves ready.','Prepare the next matchup during resets; keep bags away from the rope.'],
  ['Set out batons, soft quick-release ties, spoons and ping-pong balls.','Check each team has the same setup; mark lanes and the finish.','Collect each round’s kit before the next one starts.'],
  ['Get the prizes ready; start packing unused gear.'],
  ['Have the winner coupons / vouchers ready.'],
  ['Keep gear and bags together for cleanup; leave access routes clear.'],
  ['Count balls, basket, rope, batons, cloths, spoons and cones.','Check for gear left on the field and separate anything borrowed.'],
  ['Check all gear is packed and the field is clear.'],
  ['Keep gear out of the gathering area and leave access clear.'],
 ]},
 {id:'food-water',name:'Food & water',general:['Agree rotating cover for games and the break; hand over before leaving the station.','Check food allergies and dietary needs with the teams; label known ingredients and flag anything uncertain.','Keep water available during games, with a clear route to the station.','Count supplies against attendance and refill before the break rush.','Collect rubbish; pack leftovers and clear the station during cleanup.'],notes:[
  ['Set up food and water off the course with a clear route in.','Count supplies against attendance; check known ingredients and labels.'],
  ['Ask leaders about food allergies and dietary needs before serving; keep personal details private.'],
  ['Point out the water station during the briefing.'],
  [],
  [],
  [],
  ['Refill food and water; keep the queue off access routes.','Check ingredient questions before serving; pick up rubbish before the next game.'],
  [],
  [],
  [],
  ['Count what is left and pack unused food; keep water available.'],
  [],
  [],
  ['Pack leftover supplies, clear the station and collect nearby rubbish.'],
  [],
  ['Keep water accessible and the gathering area clear.'],
 ]},
 {id:'comms',name:'Comm',general:['Mario / Cindy: announcements, team calls and photos/video.','Test announcements before the start; check the far side of the field can hear.','Call the next team or round, plus any pauses or schedule changes from the director.','Ask before photos/video; respect anyone who wants to stay out of the shot.','Gather all five teams for the group photo; keep first aid and access routes clear.'],notes:[
  ['Check phones for photos/video and test announcements.','Confirm the Prayer lead and the order of the opening briefing.'],
  ['Call people over for the team draw.','Tell leaders where to gather and when the opening starts.'],
  ['Introduce the judges and first-aid team.','Check everyone can hear the start and stop signals.'],
  ['Gather everyone for the warm-up.','Call the first runners while the game area is prepared.'],
  ['Call the next runner and round clearly; wait for the director’s start.'],
  ['Call the next team while the basket is reset.','Let teams know when their second attempt is due.'],
  ['Let teams know Cavalry starts at 13:30; repeat any timing change from the director.'],
  ['Call the women’s round, then the men’s round.','Keep waiting teams outside the arena; repeat a stop call clearly.'],
  ['Call the next matchup from the bracket and where those teams should wait.'],
  ['Call each relay round and give teams time to get ready.','Keep spectators out of the lanes and finish area.'],
  ['Get teams ready for results and the photo; confirm the timing with the director.'],
  ['Announce the final results once the scores are checked.','Call team names clearly before vouchers are handed out.'],
  ['Mario / Cindy: gather all five teams and take photos/video.','Check photo opt-outs; keep the shot clear of first aid and access routes.'],
  ['Remind everyone to collect bags and help clean up.','Tell teams the field must be clear by 16:00.'],
  [],
  ['Call all five teams together and introduce whoever is leading Prayer.','Follow with the welcome and safety briefing.'],
 ]},
 {id:'team-leaders',name:'Team leaders',general:['Count members at the draw, after the break and before leaving.','Keep the team desk updated; sort substitutions and tell the judge about player changes.','Keep player counts equal; rotate runners and pairs so everyone willing gets a turn.','Have the next players ready when called; nobody has to join in.','Check on your team and pass concerns to first aid privately.'],notes:[
  ['Confirm who is coming and flag any missing kit or attendance change to the committee.'],
  ['Count members, note names and sort substitutions.','Invite anyone with a health concern or injury to speak privately with first aid.'],
  ['Check everyone knows the boundaries and stop signal.','Pass any concerns to first aid privately.'],
  ['Check who’s ready to play; nobody has to join in.','Have the first runner ready and agree the rotation.'],
  ['Send one runner per round. Rotate so everyone willing gets a turn.','Ask before borrowing an item or person; have the next runner ready.'],
  ['Keep player counts equal and have the team ready for both attempts.','Tell the judge about any player change before the start.'],
  ['Check on your team and dietary needs; back for Cavalry at 13:30.','Count everyone back in before the next game.'],
  ['Sort 3 bases + 1 rider per horse for the women’s / men’s round.','Check your team knows the out and stop signals.','Keep waiting members outside the arena.'],
  ['Match the agreed puller count and be ready for your matchup.','No wrapping the rope or sudden release.'],
  ['Keep runner/pair counts equal and rotate extra members.','No forced pairs or dragging; have the next runners ready off the lanes.'],
  ['Stay ready if a tie-breaker is needed; flag any missing result to the director.'],
  ['Gather the team for results; check the team name before vouchers are handed out.'],
  ['Get everyone together quickly and keep access clear.','Check who wants to stay out of photos/video.'],
  ['Count your team, check belongings and help collect rubbish.','Return borrowed items and game kit to equipment.'],
  ['Check your team is ready to leave and nothing is left behind.'],
  ['Gather and count your team before Prayer; keep access clear.'],
 ]},
];
