import assert from 'node:assert/strict';
import {defaultState,TEAM_IDS} from '../model.js';
import {recordSuccess,recordWinner,setBasketScore,finishBasketAttempt,eliminate} from '../rounds.js';
import {makeClock,startClock,pauseClock} from '../timer-model.js';
import {nextIncompleteKey,nextTarget,activeRoundKey} from '../flow-model.js';

const tests=[];const test=(name,run)=>{run();tests.push(name);console.log('PASS '+name);};
function play(s,key){s.timers[key]=makeClock(90);assert.equal(startClock(s.timers,key,100),true);s.activeKey=key;}
function finish(s,game,round){play(s,`${game}:${round}`);TEAM_IDS.forEach(id=>recordSuccess(s,game,round,id));}
function freeze(value){if(value&&typeof value==='object'){Object.values(value).forEach(freeze);Object.freeze(value);}return value;}
test('Last-numbered Borrow and Relay round wraps to earlier unfinished work',()=>{for(const game of ['borrow','relay']){const s=defaultState(),last=game==='borrow'?5:2;finish(s,game,last);assert.equal(nextIncompleteKey(s,`${game}:${last}`),game+':0');assert.deepEqual(nextTarget(s,`${game}:${last}`),{key:game+':0',label:'Round 1'});}});
test('Next follows chronological order, skips completed work and wraps',()=>{const s=defaultState();finish(s,'borrow',0);finish(s,'borrow',2);assert.equal(nextIncompleteKey(s,'borrow:0'),'borrow:1');assert.equal(nextIncompleteKey(s,'borrow:1'),'borrow:3');finish(s,'borrow',1);for(const round of [3,4,5])finish(s,'borrow',round);assert.equal(nextIncompleteKey(s,'borrow:5'),null);assert.equal(nextTarget(s,'borrow:5'),null);});
test('Contingency work follows configured rounds only',()=>{const s=defaultState();for(let round=0;round<6;round++)finish(s,'borrow',round);assert.equal(nextIncompleteKey(s,'borrow:5'),null);s.borrow.rounds=7;assert.deepEqual(nextTarget(s,'borrow:5'),{key:'borrow:6',label:'Round 7'});});
test('Basket next includes team and attempt, skips done attempts, and wraps',()=>{const s=defaultState();s.teams[0].name='Crimson';play(s,'basket:white:1');setBasketScore(s,'white',1,3);finishBasketAttempt(s,'white',1);assert.deepEqual(nextTarget(s,'basket:white:1'),{key:'basket:red:0',label:'Crimson · attempt 1'});play(s,'basket:red:0');setBasketScore(s,'red',0,2);finishBasketAttempt(s,'red',0);assert.deepEqual(nextTarget(s,'basket:red:0'),{key:'basket:red:1',label:'Crimson · attempt 2'});play(s,'basket:red:1');setBasketScore(s,'red',1,4);finishBasketAttempt(s,'red',1);assert.equal(nextIncompleteKey(s,'basket:red:1'),'basket:blue:0');});
test('Tug next excludes draft and unready opponents but finds ready matches',()=>{const s=defaultState();assert.equal(nextIncompleteKey(s,'tug:prelim'),null);s.tug.slots=[...TEAM_IDS];assert.equal(nextIncompleteKey(s,'tug:prelim'),null);s.tug.locked=true;assert.deepEqual(nextTarget(s,'tug:semi1'),{key:'tug:semi2',label:'Semifinal 2'});play(s,'tug:semi2');recordWinner(s,'semi2','green');assert.equal(nextIncompleteKey(s,'tug:semi2'),'tug:prelim');play(s,'tug:prelim');recordWinner(s,'prelim','red');assert.deepEqual(nextTarget(s,'tug:prelim'),{key:'tug:semi1',label:'Semifinal 1'});});
test('Cavalry next includes an arena that still needs setup and excludes completed division',()=>{const s=defaultState(),d=s.cavalry.divisions.women;d.active=['red','blue'];d.started=true;play(s,'cavalry:women');eliminate(s,'women','red');assert.deepEqual(nextTarget(s,'cavalry:women'),{key:'cavalry:men',label:'Round 2 · Men'});assert.equal(nextIncompleteKey(s,'cavalry:men'),'cavalry:men');});
test('Flow helpers reject unrelated keys and never mutate a frozen snapshot',()=>{const s=freeze(defaultState());assert.equal(nextIncompleteKey(s,'event:4'),null);assert.equal(nextIncompleteKey(s,null),null);assert.equal(nextIncompleteKey(s,'borrow'),'borrow:0');assert.deepEqual(nextTarget(s,'relay:0'),{key:'relay:1',label:'Round 2'});assert.equal(activeRoundKey(s),null);});
test('Active round finds a running clock and keeps an explicitly active paused clock',()=>{const s=defaultState();play(s,'relay:1');assert.equal(activeRoundKey(s),'relay:1');pauseClock(s.timers['relay:1'],200);assert.equal(activeRoundKey(s),'relay:1');s.activeKey=null;assert.equal(activeRoundKey(s),null);play(s,'borrow:2');s.activeKey='relay:1';assert.equal(activeRoundKey(s),'borrow:2');});
test('Active round excludes unstarted, disabled contingency and completed work',()=>{const s=defaultState();s.timers['borrow:0']=makeClock(90);s.activeKey='borrow:0';assert.equal(activeRoundKey(s),null);play(s,'borrow:6');assert.equal(activeRoundKey(s),null);finish(s,'borrow',0);assert.equal(activeRoundKey(s),null);for(let round=1;round<6;round++)finish(s,'borrow',round);assert.equal(activeRoundKey(s),null);});
test('Active Tug requires a ready locked match, and completed match stops following',()=>{const s=defaultState();play(s,'tug:prelim');assert.equal(activeRoundKey(s),null);s.tug.slots=[...TEAM_IDS];s.tug.locked=true;assert.equal(activeRoundKey(s),'tug:prelim');recordWinner(s,'prelim','red');assert.equal(activeRoundKey(s),null);});
test('An expired active clock remains inspectable and an event clock remains usable',()=>{const s=defaultState();play(s,'relay:0');pauseClock(s.timers['relay:0'],1000000);assert.equal(s.timers['relay:0'].remaining,0);assert.equal(activeRoundKey(s),'relay:0');play(s,'event:15');assert.equal(activeRoundKey(freeze(s)),'event:15');});
console.log(`${tests.length} flow tests passed.`);
