import assert from 'node:assert/strict';
import {defaultState,TEAM_IDS,totals,championship,validateState,gamePlaces} from '../model.js';
import {recordSuccess,recordWinner,setBasketScore,finishBasketAttempt,timerStarted,roundDone,gameDone,eliminate,cavalryPoints,resetRound,resetGame} from '../rounds.js';
import {makeClock,startClock,pauseClock,resetClock} from '../timer-model.js';
const tests=[];const test=(name,run)=>{run();tests.push(name);console.log('PASS '+name);};
function play(s,key){s.timers[key]=makeClock(90);assert.equal(startClock(s.timers,key,100),true);}
function arena(s,division,active=TEAM_IDS){const d=s.cavalry.divisions[division];d.active=[...active];d.started=true;play(s,'cavalry:'+division);}
function draw(s){s.tug.slots=[...TEAM_IDS];s.tug.locked=true;}
test('Every result path refuses points until its timer has started',()=>{const s=defaultState();draw(s);s.cavalry.divisions.women.active=[...TEAM_IDS];s.cavalry.divisions.women.started=true;assert.equal(recordSuccess(s,'borrow',0,'red'),false);assert.equal(recordSuccess(s,'borrow',0,'red',false),false);assert.equal(recordSuccess(s,'relay',0,'red'),false);assert.equal(recordWinner(s,'prelim','red'),false);assert.equal(setBasketScore(s,'red',0,1),false);assert.equal(finishBasketAttempt(s,'red',0),false);assert.equal(eliminate(s,'women','red'),false);assert.deepEqual(s.finished,[]);assert.deepEqual(s.borrow.scores[0],Array(7).fill(null));assert.equal(s.tug.winners.prelim,null);});
test('A configured clock or another started round is not enough to award points',()=>{const s=defaultState();s.timers['borrow:0']=makeClock(90);assert.equal(timerStarted(s,'borrow:0'),false);assert.equal(recordSuccess(s,'borrow',0,'red'),false);play(s,'borrow:1');assert.equal(recordSuccess(s,'borrow',0,'red'),false);});
test('Failure never consumes a success rank; taps cannot overwrite results',()=>{const s=defaultState();play(s,'borrow:0');recordSuccess(s,'borrow',0,'red',false);recordSuccess(s,'borrow',0,'blue');recordSuccess(s,'borrow',0,'blue');recordSuccess(s,'borrow',0,'yellow');recordSuccess(s,'borrow',0,'green');recordSuccess(s,'borrow',0,'white');assert.deepEqual(s.borrow.scores.map(r=>r[0]),[0,5,4,3,2]);assert.equal(roundDone(s,'borrow:0'),true);assert.equal(recordSuccess(s,'borrow',0,'red'),false);});
test('Five successful finishes receive 5/4/3/2/2 and persist',()=>{const s=defaultState();play(s,'borrow:2');TEAM_IDS.forEach(id=>recordSuccess(s,'borrow',2,id));assert.deepEqual(s.borrow.scores.map(r=>r[2]),[5,4,3,2,2]);assert.deepEqual(validateState(s),s);});
test('Paused and expired timers allow results after being started',()=>{const s=defaultState();play(s,'relay:1');pauseClock(s.timers['relay:1'],200);assert.equal(recordSuccess(s,'relay',1,'white'),true);startClock(s.timers,'relay:1',300);pauseClock(s.timers['relay:1'],1000000);assert.equal(s.timers['relay:1'].remaining,0);assert.equal(recordSuccess(s,'relay',1,'green'),true);});
test('Relay arrival order produces unique places and locks',()=>{const s=defaultState();play(s,'relay:1');[...TEAM_IDS].reverse().forEach(id=>recordSuccess(s,'relay',1,id));assert.deepEqual(s.relay.scores.map(r=>r[1]),[5,4,3,2,1]);assert.equal(roundDone(s,'relay:1'),true);});
test('Timer reset requires Play again before any more round points',()=>{const s=defaultState();play(s,'borrow:0');assert.equal(recordSuccess(s,'borrow',0,'red'),true);resetClock(s.timers['borrow:0']);assert.equal(recordSuccess(s,'borrow',0,'blue'),false);const restored=validateState(s);assert.equal(timerStarted(restored,'borrow:0'),false);startClock(restored.timers,'borrow:0',200);assert.equal(recordSuccess(restored,'borrow',0,'blue'),true);});
test('Tug uses the corresponding started match timer and locks winners',()=>{const s=defaultState();draw(s);play(s,'tug:semi2');assert.equal(recordWinner(s,'prelim','red'),false);play(s,'tug:prelim');assert.equal(recordWinner(s,'prelim','red'),true);assert.equal(recordWinner(s,'prelim','blue'),false);assert.equal(recordWinner(s,'semi1','red'),false);play(s,'tug:semi1');assert.equal(recordWinner(s,'semi1','red'),true);play(s,'tug:semi2');assert.equal(recordWinner(s,'semi2','white'),true);play(s,'tug:final');assert.equal(recordWinner(s,'final','white'),true);assert.equal(gameDone(s,'tug'),true);assert.deepEqual(gamePlaces(s,'tug'),[2,5,3,3,1]);assert.equal(recordWinner(s,'final','red'),false);});
test('Basket counting and finish both require the specific started attempt',()=>{const s=defaultState();play(s,'basket:red:0');assert.equal(setBasketScore(s,'blue',0,10),false);assert.equal(setBasketScore(s,'red',1,10),false);assert.equal(setBasketScore(s,'red',0,10),true);assert.equal(finishBasketAttempt(s,'red',0),true);assert.equal(setBasketScore(s,'red',0,11),false);assert.equal(finishBasketAttempt(s,'red',0),false);assert.deepEqual(s.finished,['basket:red:0']);assert.equal(gameDone(s,'basket'),false);});
test('Basket awards overview points only when all ten attempts finish',()=>{const s=defaultState();for(const id of TEAM_IDS)for(const attempt of [0,1]){play(s,`basket:${id}:${attempt}`);setBasketScore(s,id,attempt,10);if(id!=='white'||attempt!==1)finishBasketAttempt(s,id,attempt);}assert.deepEqual(totals(s,'basket'),[10,10,10,10,10]);assert.equal(championship(s).completed,0);finishBasketAttempt(s,'white',1);assert.equal(gameDone(s,'basket'),true);assert.equal(championship(s).completed,1);assert.deepEqual(championship(s).rows.map(row=>row.total),[5,5,5,5,5]);});
test('Cavalry requires a started arena and timer, rejects repeated eliminations, and awards last horse five',()=>{const s=defaultState(),d=s.cavalry.divisions.women;d.active=[...TEAM_IDS];assert.equal(eliminate(s,'women','red'),false);arena(s,'women');TEAM_IDS.slice(0,4).forEach(id=>assert.equal(eliminate(s,'women',id),true));assert.equal(eliminate(s,'women','red'),false);assert.equal(eliminate(s,'women','white'),false);assert.deepEqual(cavalryPoints(s,'women'),[1,2,3,4,5]);assert.equal(roundDone(s,'cavalry:women'),true);assert.deepEqual(validateState(s),s);});
test('Cavalry timer reset locks eliminations until restarted',()=>{const s=defaultState();arena(s,'women');eliminate(s,'women','red');resetClock(s.timers['cavalry:women']);assert.equal(eliminate(s,'women','blue'),false);assert.equal(validateState(s).timers['cavalry:women'].started,false);startClock(s.timers,'cavalry:women',200);assert.equal(eliminate(s,'women','blue'),true);});
test('Cavalry nonparticipants earn zero; incomplete divisions award no overview totals',()=>{const s=defaultState();arena(s,'women',['red','blue']);eliminate(s,'women','red');assert.deepEqual(cavalryPoints(s,'women'),[4,5,0,0,0]);assert.deepEqual(totals(s,'cavalry'),[null,null,null,null,null]);assert.equal(gameDone(s,'cavalry'),false);});
test('Cavalry completed divisions automatically enter championship',()=>{const s=defaultState();for(const division of ['women','men']){arena(s,division);TEAM_IDS.slice(0,4).forEach(id=>eliminate(s,division,id));}assert.deepEqual(totals(s,'cavalry'),[2,4,6,8,10]);assert.equal(gameDone(s,'cavalry'),true);assert.equal(championship(s).completed,1);assert.equal(championship(s).rows[0].id,'white');});
test('Borrow and relay enter overview after their final default round and stay locked',()=>{for(const game of ['borrow','relay']){const s=defaultState(),count=game==='borrow'?6:3;for(let round=0;round<count;round++){play(s,`${game}:${round}`);TEAM_IDS.forEach(id=>recordSuccess(s,game,round,id));assert.equal(championship(s).completed,round===count-1?1:0);}assert.equal(gameDone(s,game),true);assert.equal(recordSuccess(s,game,0,'red'),false);}});
test('Round reset clears its scores and timer gate while preserving other rounds',()=>{const s=defaultState();play(s,'borrow:0');recordSuccess(s,'borrow',0,'red');play(s,'borrow:1');recordSuccess(s,'borrow',1,'blue');resetRound(s,'borrow:0');assert.equal(s.borrow.scores[0][0],null);assert.equal(s.borrow.scores[1][1],5);assert.equal(s.timers['borrow:0'],undefined);assert.equal(recordSuccess(s,'borrow',0,'red'),false);});
test('Reset preliminary invalidates dependent results and timers, keeping other semi',()=>{const s=defaultState();draw(s);for(const [match,id] of [['prelim','red'],['semi1','red'],['semi2','white'],['final','white']]){play(s,'tug:'+match);recordWinner(s,match,id);}resetRound(s,'tug:prelim');assert.deepEqual(s.tug.winners,{prelim:null,semi1:null,semi2:'white',final:null});assert.equal(s.timers['tug:final'],undefined);assert.equal(s.timers['tug:semi1'],undefined);assert.equal(timerStarted(s,'tug:semi2'),true);assert.equal(gameDone(s,'tug'),false);assert.equal(championship(s).completed,0);});
test('Attempt completion persists and reset unlocks it',()=>{const s=defaultState();play(s,'basket:red:0');finishBasketAttempt(s,'red',0);assert.equal(roundDone(validateState(s),'basket:red:0'),true);resetRound(s,'basket:red:0');assert.equal(roundDone(s,'basket:red:0'),false);assert.equal(s.basket.scores[0][0],null);assert.equal(timerStarted(s,'basket:red:0'),false);});
test('Game reset withdraws overview points while preserving other game data and names',()=>{const s=defaultState();s.teams[0].name='Crimson';s.notes[4]='Ready';for(let round=0;round<6;round++){play(s,'borrow:'+round);TEAM_IDS.forEach(id=>recordSuccess(s,'borrow',round,id));}s.basket.scores[0][0]=10;assert.equal(championship(s).completed,1);resetGame(s,'borrow');assert.equal(championship(s).completed,0);assert.equal(s.borrow.scores[0][0],null);assert.equal(s.basket.scores[0][0],10);assert.equal(s.teams[0].name,'Crimson');assert.equal(s.notes[4],'Ready');assert.equal(timerStarted(s,'borrow:0'),false);});
test('Old backups preserve partial results but require Play before more points',()=>{const s=defaultState();delete s.finished;assert.deepEqual(validateState(s).finished,[]);s.finished=['basket:red:0'];assert.throws(()=>validateState(s));s.finished=[];s.relay.scores[0][0]=1;const restored=validateState(s);assert.equal(restored.relay.scores[0][0],1);assert.equal(timerStarted(restored,'relay:0'),false);assert.equal(recordSuccess(restored,'relay',0,'blue'),false);play(restored,'relay:0');assert.equal(recordSuccess(restored,'relay',0,'blue'),true);assert.deepEqual(restored.relay.scores.map(row=>row[0]),[1,2,null,null,null]);});
test('Continuing legacy relay places with gaps preserves results and remains restorable',()=>{const s=defaultState();s.relay.scores[0][0]=5;s.relay.scores[2][0]=2;const restored=validateState(s);play(restored,'relay:0');for(const id of ['blue','green','white'])assert.equal(recordSuccess(restored,'relay',0,id),true);assert.deepEqual(restored.relay.scores.map(row=>row[0]),[5,1,2,3,4]);assert.equal(roundDone(restored,'relay:0'),true);assert.deepEqual(validateState(restored),restored);});
test('Continuing legacy borrow awards consumes each saved award and keeps failures at zero',()=>{const s=defaultState();s.borrow.scores[0][0]=4;s.borrow.scores[2][0]=2;const restored=validateState(s);play(restored,'borrow:0');assert.equal(recordSuccess(restored,'borrow',0,'blue',false),true);assert.equal(recordSuccess(restored,'borrow',0,'green'),true);assert.equal(recordSuccess(restored,'borrow',0,'white'),true);assert.deepEqual(restored.borrow.scores.map(row=>row[0]),[4,0,2,5,3]);assert.deepEqual(validateState(restored),restored);});
test('Both equal two-point borrow awards remain available when a legacy round resumes',()=>{const s=defaultState();s.borrow.scores[0][0]=2;const restored=validateState(s);play(restored,'borrow:0');for(const id of ['blue','yellow','green','white'])assert.equal(recordSuccess(restored,'borrow',0,id),true);assert.deepEqual(restored.borrow.scores.map(row=>row[0]),[2,5,4,3,2]);assert.deepEqual(validateState(restored),restored);});
test('An untouched legacy clock with partial results does not bypass Play',()=>{const s=defaultState();s.borrow.scores[0][0]=5;s.timers['borrow:0']=makeClock(90);delete s.timers['borrow:0'].started;const restored=validateState(s);assert.equal(timerStarted(restored,'borrow:0'),false);assert.equal(recordSuccess(restored,'borrow',0,'blue'),false);startClock(restored.timers,'borrow:0',200);assert.equal(recordSuccess(restored,'borrow',0,'blue'),true);});
test('Active paused match persists and scoped resets clear its shortcut',()=>{const s=defaultState();play(s,'borrow:0');pauseClock(s.timers['borrow:0'],200);s.activeKey='borrow:0';assert.equal(validateState(s).activeKey,'borrow:0');resetRound(s,'borrow:0');assert.equal(s.activeKey,null);});
console.log(`${tests.length} round workflow tests passed.`);
